version: "3.9"

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql-3
    ports:
      - "3346:3306"
    volumes:
      - ./:/app/
    environment:
      MYSQL_DATABASE: web_customer_tracker
      MYSQL_USER: customer
      MYSQL_PASSWORD: customer
      MYSQL_ROOT_PASSWORD: MyLu805881!
    networks:
      - internal

  rabbitmq-container:
    image: rabbitmq:3.11-management
    hostname: rabbitmq-container
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - internal

  app:
    container_name: demo-2
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq-container
    volumes:
      - ./:/app/app
    links:
      - db
    networks:
      - internal
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/web_customer_tracker?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - spring_rabbitmq_host=rabbitmq-container
      - spring_rabbitmq_port=5672

networks:
  internal:
    name: internal
